apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: sleep-replicaset
  namespace: tests
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      labels:
        app: sleep
    spec:
      containers:
      - name: sleep-container
        image: busybox
        command: ["sleep", "infinity"]
        volumeMounts:
        - mountPath: /app
          name: app-volume
      volumes:
      - name: app-volume
        persistentVolumeClaim:
          claimName: app-pvc-replicaset
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
  namespace: tests
spec:
  storageClassName: netrunner-nfs-ssd-snaps
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: sleep-replicaset2
  namespace: tests
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      labels:
        app: sleep
    spec:
      containers:
      - name: sleep-container
        image: busybox
        command: ["sleep", "infinity"]
        volumeMounts:
        - mountPath: /app
          name: app-volume
      volumes:
      - name: app-volume
        persistentVolumeClaim:
          claimName: app-pvc-replicaset2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc-replicaset2
  namespace: tests
spec:
  storageClassName: netrunner-nfs-ssd-snaps
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
---